# Generated by Django 2.0.13 on 2019-10-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField(default=0)),
                ('last_updated_model', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
