# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iati_organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codelist',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('count', models.CharField(blank=True, max_length=10, null=True)),
                ('fields', models.CharField(blank=True, max_length=255, null=True)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(default=b'', max_length=255)),
                ('filetype', models.IntegerField(choices=[
                 (1, b'Activity'), (2, b'Organisation')], default=1)),
                ('source_url', models.URLField(max_length=255)),
                ('iati_version', models.CharField(default=b'', max_length=10)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('time_to_parse', models.CharField(default=None, max_length=40, null=True)),
                ('last_found_in_registry', models.DateTimeField(default=None, null=True)),
                ('is_parsed', models.BooleanField(default=False)),
                ('added_manually', models.BooleanField(default=True)),
                ('sha1', models.CharField(blank=True, default=b'', max_length=40)),
                ('note_count', models.IntegerField(default=0)),
                ('export_in_progress', models.BooleanField(default=False)),
                ('parse_in_progress', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'IATI XML sources',
            },
        ),
        migrations.CreateModel(
            name='DatasetNote',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_identifier', models.CharField(max_length=140)),
                ('exception_type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('field', models.CharField(default=b'', max_length=100)),
                ('message', models.CharField(default=0, max_length=150)),
                ('line_number', models.IntegerField(null=True)),
                ('dataset', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='iati_synchroniser.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_id', models.CharField(max_length=255)),
                ('publisher_iati_id', models.CharField(max_length=100)),
                ('name', models.CharField(default=b'', max_length=55)),
                ('display_name', models.CharField(max_length=255)),
                ('organisation',
                 models.OneToOneField(default=None,
                                      null=True,
                                      on_delete=django.db.models.deletion.SET_NULL,
                                      to='iati_organisation.Organisation')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='publisher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='iati_synchroniser.Publisher'),
        ),
    ]
