# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='iati_version',
            field=models.CharField(default=b'2.02', max_length=10),
        ),
    ]
