# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='organisation',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iati_organisation.Organisation'),
        ),
    ]
