# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0002_auto_20151210_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iatixmlsource',
            name='last_hash',
        ),
        migrations.RemoveField(
            model_name='iatixmlsource',
            name='oipa_activity_count',
        ),
        migrations.RemoveField(
            model_name='iatixmlsource',
            name='update_interval',
        ),
        migrations.RemoveField(
            model_name='iatixmlsource',
            name='xml_activity_count',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='OIPA_total_activity_count',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='XML_total_activity_count',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='default_interval',
        ),
        migrations.AlterField(
            model_name='iatixmlsource',
            name='ref',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='iatixmlsource',
            name='type',
            field=models.IntegerField(choices=[(1, b'Activity standard'), (2, b'Organisation standard')], default=1),
        ),
    ]
