# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0003_auto_20160111_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='iatixmlsource',
            name='note_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iatixmlsource',
            name='parse_notes',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='iatixmlsource',
            name='sha1',
            field=models.CharField(blank=True, default=b'', max_length=40),
        ),
    ]
