# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0004_auto_20160601_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='IatiXmlSourceNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_identifier', models.CharField(max_length=20)),
                ('exception_type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('field', models.TextField(default=0, max_length=1000)),
                ('line_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='iatixmlsource',
            name='note_count',
        ),
        migrations.RemoveField(
            model_name='iatixmlsource',
            name='parse_notes',
        ),
        migrations.AddField(
            model_name='iatixmlsourcenote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_synchroniser.IatiXmlSource'),
        ),
    ]
