# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0005_auto_20170613_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetnote',
            name='variable',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
