# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0007_iatixmlsource_note_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='iatixmlsourcenote',
            name='message',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='iatixmlsourcenote',
            name='field',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
