# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0008_auto_20160606_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iatixmlsourcenote',
            name='field',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
