# Generated by Django 2.0.4 on 2018-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0008_auto_20171106_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='filetype',
            field=models.IntegerField(choices=[(1, 'Activity'), (2, 'Organisation')], default=1),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='iati_version',
            field=models.CharField(default='2.02', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='sha1',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datasetnote',
            name='field',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datasetnote',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='', max_length=55),
        ),
    ]
