# Generated by Django 2.0.6 on 2018-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0009_auto_20180430_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelist',
            name='count',
            field=models.CharField(blank=True, help_text='Count of different codes in this codelist', max_length=10, null=True),
        ),
    ]
