# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0009_auto_20160606_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='iatixmlsource',
            name='time_to_parse',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
