# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0010_iatixmlsource_time_to_parse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iatixmlsourcenote',
            name='iati_identifier',
            field=models.CharField(max_length=140),
        ),
    ]
