# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0011_auto_20160622_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iatixmlsource',
            name='type',
            field=models.IntegerField(choices=[(1, b'Activity'), (2, b'Organisation')], default=1),
        ),
    ]
