# Generated by Django 2.0.6 on 2019-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0012_auto_20190221_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='source_url',
            field=models.TextField(),
        ),
    ]
