# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-18 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_organisation', '0007_auto_20160606_0304'),
        ('iati_synchroniser', '0012_auto_20160719_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.Organisation'),
        ),
    ]
