# Generated by Django 2.0.13 on 2019-06-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0013_auto_20190222_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='activities_count_in_database',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='activities_count_in_xml',
            field=models.IntegerField(default=0),
        ),
    ]
