# Generated by Django 2.0.13 on 2019-06-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0013_auto_20190222_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='package_count',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
