# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0013_publisher_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='org_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.Organisation', unique=True),
        ),
    ]
