# Generated by Django 2.0.13 on 2019-06-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0014_publisher_package_count'),
        ('iati_synchroniser', '0014_add_activity_count_in_xml_and_database'),
    ]

    operations = [
    ]
