# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0014_auto_20161024_1451'),
        ('permissions', '0002_auto_20161031_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IatiXmlSource',
            new_name='Dataset',
        ),
        migrations.RenameModel(
            old_name='IatiXmlSourceNote',
            new_name='DatasetNote',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='org_name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='org_id',
            new_name='publisher_iati_id',
        ),
        migrations.AddField(
            model_name='publisher',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        # TODO: not working on empty table :( - 2016-11-01
        # migrations.RunSQL(
        #     'ALTER TABLE "iati_synchroniser_dataset" DROP CONSTRAINT iati_synchr_dataset_id_c6e8fcc4_fk_iati_synchroniser_dataset_id',
        # ),
        # migrations.RunSQL(
        #     'ALTER TABLE "permissions_organisationadmingroup" DROP CONSTRAINT permissions_organisationadmingroup_publisher_id_f12aebbd_fk',
        # ),
        # migrations.RunSQL(
        #     'ALTER TABLE "permissions_organisationgroup" DROP CONSTRAINT permissions_organisationgroup_publisher_id_840beca0_fk',
        # ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        # migrations.RunSQL(
        #     'ALTER TABLE "iati_synchroniser_publisher" ALTER COLUMN "id" type varchar(255) USING CAST(id AS varchar(255));',
        # ),
        # migrations.RunSQL(
        #     'ALTER TABLE "iati_synchroniser_dataset" ALTER COLUMN "publisher_id" type varchar(255) USING CAST(publisher_id AS varchar(255));',
        # ),
        # migrations.RunSQL(
        #     'ALTER TABLE "iati_synchroniser_dataset" ADD CONSTRAINT iati_synchr_dataset_id_c6e8fcc4_fk_iati_synchroniser_dataset_id FOREIGN KEY (publisher_id) REFERENCES iati_synchroniser_publisher (id)',
        # ),
        # migrations.RunSQL(
        #     'ALTER TABLE "permissions_organisationadmingroup" ALTER COLUMN "publisher_id" type varchar(255) USING CAST(publisher_id AS varchar(255));',
        # ),
        # migrations.RunSQL(
        #     'ALTER TABLE "permissions_organisationadmingroup" ADD CONSTRAINT permissions_organisationadmingroup_publisher_id_f12aebbd_fk FOREIGN KEY (publisher_id) REFERENCES iati_synchroniser_publisher (id)',
        # ),
        # migrations.RunSQL(
        #     'ALTER TABLE "permissions_organisationgroup" ALTER COLUMN "publisher_id" type varchar(255) USING CAST(publisher_id AS varchar(255));',
        # ),
        # migrations.RunSQL(
        #     'ALTER TABLE "permissions_organisationgroup" ADD CONSTRAINT permissions_organisationgroup_publisher_id_840beca0_fk FOREIGN KEY (publisher_id) REFERENCES iati_synchroniser_publisher (id)',
        # ),
    ]
