# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0014_auto_20161024_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IatiXmlSource',
            new_name='Dataset',
        ),
        migrations.RenameModel(
            old_name='IatiXmlSourceNote',
            new_name='DatasetNote',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='org_name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='org_id',
            new_name='publisher_iati_id',
        ),
        migrations.AddField(
            model_name='publisher',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.RunSQL(
            'ALTER TABLE "iati_synchroniser_publisher" ALTER COLUMN "id" type varchar(255) USING CAST(id AS varchar(255));',
        ),
        migrations.RunSQL(
            'ALTER TABLE "iati_synchroniser_dataset" ALTER COLUMN "publisher_id" type varchar(255) USING CAST(publisher_id AS varchar(255));',
        ),
    ]
