# Generated by Django 2.0.13 on 2021-01-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0015_merge_20190619_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_synchroniser.Publisher'),
        ),
    ]
