# Generated by Django 2.0.13 on 2020-11-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0016_auto_20201029_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='iati_version',
            field=models.CharField(default='2.02', max_length=255),
        ),
    ]
