# Generated by Django 2.0.13 on 2021-01-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0016_auto_20210111_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='iati_version',
            field=models.CharField(default='2.02', max_length=255),
        ),
    ]
