# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0016_auto_20161026_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['name'], 'verbose_name_plural': 'IATI XML sources'},
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='type',
            new_name='filetype',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='iati_standard_version',
            new_name='iati_version',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='ref',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
