# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0017_auto_20161026_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='source_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_iati_id',
            field=models.CharField(max_length=100),
        ),
    ]
