# Generated by Django 2.0.13 on 2020-02-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0018_dataset_validation_md5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='validation_md5',
            new_name='validation_sha1',
        ),
    ]
