# Generated by Django 2.0.13 on 2020-08-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0018_auto_20200730_1328'),
        ('iati_synchroniser', '0018_dataset_sync_sha1'),
    ]

    operations = [
    ]
