# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0018_auto_20161026_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='image_url',
        ),
    ]
