# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0019_remove_publisher_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetnote',
            old_name='source',
            new_name='dataset',
        ),
    ]
