# Generated by Django 2.0.13 on 2020-11-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0019_merge_20200804_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_synchroniser.Publisher'),
        ),
    ]
