# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0020_auto_20161027_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelist',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
