# Generated by Django 2.0.13 on 2020-12-18 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0020_auto_20201102_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetFailedPickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_synchroniser.Dataset')),
            ],
        ),
    ]
