# Generated by Django 2.0.13 on 2020-12-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0021_datasetfailedpickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetfailedpickup',
            name='exception_message',
        ),
        migrations.AddField(
            model_name='datasetfailedpickup',
            name='error_detail',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='datasetfailedpickup',
            name='is_http_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetfailedpickup',
            name='status_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
