# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0021_auto_20170123_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='export_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='parse_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
