# Generated by Django 2.0.13 on 2021-03-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0021_datasetfailedpickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUpdateDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
