# Generated by Django 2.0.13 on 2021-01-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0022_auto_20201220_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetfailedpickup',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='DatasetFailedPickup',
        ),
    ]
