# Generated by Django 2.0.13 on 2021-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0022_datasetupdatedates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetfailedpickup',
            name='dataset',
        ),
        migrations.AddField(
            model_name='datasetfailedpickup',
            name='dataset_filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasetfailedpickup',
            name='dataset_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datasetfailedpickup',
            name='publisher_identifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasetfailedpickup',
            name='publisher_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
