# Generated by Django 2.0.13 on 2021-01-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0023_auto_20210110_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetFailedPickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_http_error', models.BooleanField(default=False)),
                ('status_code', models.CharField(max_length=100, null=True)),
                ('error_detail', models.TextField(max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_synchroniser.Dataset')),
            ],
        ),
    ]
