# Generated by Django 2.0.13 on 2021-03-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0024_datasetdownloadsfinished_datasetdownloadsstarted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatasetDownloadsFinished',
            new_name='AsyncTasksFinished',
        ),
    ]
