# Generated by Django 2.0.13 on 2021-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0025_auto_20210331_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterruptIncrementalParse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
