# Generated by Django 2.0.13 on 2021-09-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0026_dataset_old_date_marker'),
        ('iati_synchroniser', '0026_interruptincrementalparse'),
    ]

    operations = [
    ]
