# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('iati_vocabulary', '0001_initial'),
        ('iati_codelists', '0001_initial'),
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('object_id', models.CharField(max_length=250, null=True, verbose_name=b'related object')),
                ('organisation_identifier', models.CharField(max_length=150, null=True, verbose_name=b'organisation_identifier')),
                ('ref', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('value_date', models.DateField(null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name=b'xml Parent')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Language')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=500)),
                ('iso_date', models.DateField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='doc_categories', to='iati_codelists.DocumentCategory')),
                ('file_format', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_formats', to='iati_codelists.FileFormat')),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='iati_codelists.Language')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLinkTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentlinktitles', to='iati_organisation.DocumentLink')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_identifier', models.CharField(db_index=True, max_length=150, unique=True)),
                ('last_updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('reported_in_iati', models.BooleanField(default=True)),
                ('primary_name', models.CharField(db_index=True, max_length=150)),
                ('default_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
                ('default_lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Language')),
                ('iati_standard_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Version')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='iati_organisation.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationNarrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name=b'related object')),
                ('content', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Language')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationReportingOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_org_identifier', models.CharField(max_length=250, null=True)),
                ('secondary_reporter', models.BooleanField(default=False)),
                ('org_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.OrganisationType')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_org', to='iati_organisation.Organisation')),
                ('reporting_org', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_by_orgs', to='iati_organisation.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientCountryBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.Country')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_country_budget', to='iati_organisation.Organisation')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.BudgetStatus')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientOrgBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_org_identifier', models.CharField(max_length=150, null=True, verbose_name=b'recipient_org_identifier')),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_org', to='iati_organisation.Organisation')),
                ('recipient_org', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieving_org', to='iati_organisation.Organisation')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.BudgetStatus')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientRegionBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary_uri', models.URLField(blank=True, null=True)),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_region_budget', to='iati_organisation.Organisation')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.Region')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.BudgetStatus')),
                ('vocabulary', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iati_vocabulary.RegionVocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='TotalBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('value_date', models.DateField(null=True)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_budget', to='iati_organisation.Organisation')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.BudgetStatus')),
            ],
        ),
        migrations.CreateModel(
            name='TotalExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(null=True)),
                ('period_end', models.DateField(null=True)),
                ('value_date', models.DateField(null=True)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_expenditure', to='iati_organisation.Organisation')),
            ],
        ),
        migrations.AddField(
            model_name='documentlink',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentlinks', to='iati_organisation.Organisation'),
        ),
        migrations.AddField(
            model_name='documentlink',
            name='recipient_countries',
            field=models.ManyToManyField(blank=True, related_name='recipient_countries', to='geodata.Country'),
        ),
        migrations.AlterIndexTogether(
            name='organisationnarrative',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
