# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='modified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='ready_to_publish',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
