
# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.contenttypes.management import update_contenttypes
import django.db.models.deletion

def remove_organisations(apps, schema_editor):
    """
    convert all transaction's xdr values
    takes ~20 mins
    """
    update_contenttypes(apps.get_app_config('iati'), interactive=False) # make sure all content types exist
    
    try: # don't run on first migration
        Organisation = apps.get_model('iati_organisation', 'Organisation')
    except:
        return

    Organisation.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0003_auto_20160204_1305'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('iati_organisation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_organisations),
    ]
