# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0001_initial'),
        ('geodata', '0001_initial'),
        ('iati_organisation', '0002_auto_20170307_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLinkRecipientCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Document link categories',
            },
        ),
        migrations.CreateModel(
            name='OrganisationDocumentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=500)),
                ('iso_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationDocumentLinkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.DocumentCategory')),
                ('document_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.OrganisationDocumentLink')),
            ],
            options={
                'verbose_name_plural': 'Document link categories',
            },
        ),
        migrations.CreateModel(
            name='OrganisationDocumentLinkLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.OrganisationDocumentLink')),
                ('language', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Language')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientCountryBudgetLine',
            fields=[
                ('ref', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('value_date', models.DateField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipientOrgBudgetLine',
            fields=[
                ('ref', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('value_date', models.DateField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipientRegionBudgetLine',
            fields=[
                ('ref', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('value_date', models.DateField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TotalBudgetLine',
            fields=[
                ('ref', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('value_date', models.DateField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TotalExpenditureLine',
            fields=[
                ('ref', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=14, null=True)),
                ('value_date', models.DateField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
                ('total_expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.TotalExpenditure')),
            ],
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='language',
        ),
        migrations.RemoveField(
            model_name='documentlink',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='documentlink',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='documentlink',
            name='language',
        ),
        migrations.RemoveField(
            model_name='documentlink',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='documentlink',
            name='recipient_countries',
        ),
        migrations.AddField(
            model_name='recipientcountrybudget',
            name='value_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recipientorgbudget',
            name='value_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recipientregionbudget',
            name='value_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='documentlinktitle',
            name='document_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.OrganisationDocumentLink'),
        ),
        migrations.AlterField(
            model_name='recipientcountrybudget',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_country_budgets', to='iati_organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='recipientorgbudget',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='recipientorgbudget',
            name='recipient_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieving_org', to='iati_organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='totalbudget',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_budgets', to='iati_organisation.Organisation'),
        ),
        migrations.DeleteModel(
            name='BudgetLine',
        ),
        migrations.DeleteModel(
            name='DocumentLink',
        ),
        migrations.AddField(
            model_name='totalbudgetline',
            name='total_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.TotalBudget'),
        ),
        migrations.AddField(
            model_name='recipientregionbudgetline',
            name='recipient_region_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.RecipientRegionBudget'),
        ),
        migrations.AddField(
            model_name='recipientorgbudgetline',
            name='recipient_org_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.RecipientOrgBudget'),
        ),
        migrations.AddField(
            model_name='recipientcountrybudgetline',
            name='recipient_country_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.RecipientCountryBudget'),
        ),
        migrations.AddField(
            model_name='organisationdocumentlink',
            name='categories',
            field=models.ManyToManyField(through='iati_organisation.OrganisationDocumentLinkCategory', to='iati_codelists.DocumentCategory'),
        ),
        migrations.AddField(
            model_name='organisationdocumentlink',
            name='file_format',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.FileFormat'),
        ),
        migrations.AddField(
            model_name='organisationdocumentlink',
            name='language',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Language'),
        ),
        migrations.AddField(
            model_name='organisationdocumentlink',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.Organisation'),
        ),
        migrations.AddField(
            model_name='organisationdocumentlink',
            name='recipient_countries',
            field=models.ManyToManyField(blank=True, related_name='recipient_countries', through='iati_organisation.DocumentLinkRecipientCountry', to='geodata.Country'),
        ),
        migrations.AddField(
            model_name='documentlinkrecipientcountry',
            name='document_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.OrganisationDocumentLink'),
        ),
        migrations.AddField(
            model_name='documentlinkrecipientcountry',
            name='recipient_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.Country'),
        ),
    ]
