# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_organisation', '0003_organisation_primary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationname',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.Organisation'),
        ),
    ]
