# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_organisation', '0004_auto_20160422_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationname',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='iati_organisation.Organisation'),
        ),
    ]
