# Generated by Django 2.0.13 on 2020-10-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_organisation', '0006_organisation_last_updated_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientcountrybudgetline',
            name='ref',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='recipientorgbudgetline',
            name='ref',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='recipientregionbudgetline',
            name='ref',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='totalbudgetline',
            name='ref',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
