# Generated by Django 2.0.13 on 2020-10-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_organisation', '0007_auto_20201021_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalexpenditureline',
            name='ref',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
