# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_organisation', '0007_auto_20160606_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationreportingorganisation',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_org', to='iati_organisation.Organisation'),
        ),
    ]
