# Generated by Django 2.0.6 on 2018-07-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='added_manually',
            field=models.BooleanField(default=False),
        ),
    ]
