# Generated by Django 2.0.6 on 2018-12-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_remove_country_capital_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
