# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_convert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyaverage',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True),
        ),
    ]
