# Generated by Django 2.0.6 on 2018-08-12 23:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iati', '0016_resultindicator_aggregation_status'),
        ('iati_codelists', '0010_aidtype_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('cumulative_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('cumulative_expenditure', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iati.Activity')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency')),
            ],
        ),
    ]
