# Generated by Django 2.0.6 on 2018-10-11 10:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0011_update_sector_vocabulary'),
        ('unesco', '0001_added_transaction_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorBudgetBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Sector')),
                ('transaction_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.TransactionBalance')),
            ],
        ),
    ]
