# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetypecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
