# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name': 'Document category', 'verbose_name_plural': 'Document categories'},
        ),
    ]
