# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0004_auto_20160602_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetstatus',
            name='code',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='budgetstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='policysignificance',
            name='code',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
