# Generated by Django 2.0.4 on 2018-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0004_auto_20180430_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidtypecategory',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
