# Generated by Django 2.0.4 on 2018-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0005_auto_20180515_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategorycategory',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
