# Generated by Django 2.0.6 on 2018-07-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0005_tagvocabulary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagVocabulary',
            new_name='TagCodelist',
        ),
    ]
