# Generated by Django 2.0.6 on 2018-07-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0006_auto_20180710_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagCodelist',
            new_name='TagVocabulary',
        ),
    ]
