# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0006_add_budget_status_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRSChannelCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default=b'')),
            ],
        ),
    ]
