# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-22 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0007_crschannelcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetypecategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
