# Generated by Django 2.0.6 on 2018-07-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0007_auto_20180710_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagVocabulary',
        ),
    ]
