# Generated by Django 2.0.6 on 2018-07-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0008_delete_tagvocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.TextField(),
        ),
    ]
