# Generated by Django 2.0.6 on 2019-01-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0010_aidtype_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetNotProvided',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
