# Generated by Django 2.0.6 on 2018-08-08 10:46

from django.db import migrations

# NOTE: This whole migration file is made to correct the 'unesco_sector_importer.py' script issue
# the script is mixing up the files, so this migration will fix the mix up
# IF THE SCRIPT IS FIXED TO USE THE CORRECT FILES THIS WHOLE MIGRATION FILE SHOULD BE DELETED!!

class Migration(migrations.Migration):

    def update_sector_vocabulary(apps, schema_editor):
        # This method is purely to switch the incorrect vocabulary id's for sectors

        Sector = apps.get_model('iati_codelists', 'Sector')
        Vocabulary = apps.get_model('iati_vocabulary', 'SectorVocabulary')

        # So these are the actual strategies and plans sectors and their vocabulary id should be 98
        sap_sectors_codes = list(Sector.objects.filter(vocabulary_id=99).values_list('code', flat=True))

        # These are the actual unesco specific sectors and their vocabulary id should be 99
        spec_sectors_codes = list(Sector.objects.filter(vocabulary_id=98).values_list('code', flat=True))

        # And here we make the corrections for those sectors
        for sector in Sector.objects.filter(pk__in=sap_sectors_codes):
            sector.vocabulary = Vocabulary.objects.get(code=98)
            sector.save()

        for sectorz in Sector.objects.filter(pk__in=spec_sectors_codes):
            sectorz.vocabulary = Vocabulary.objects.get(code=99)
            sectorz.save()

    def re_update_sector_vocabulary(apps, schema_editor):
        # this makes no sense
        pass

    dependencies = [
        ('iati_codelists', '0010_aidtype_vocabulary'),
    ]

    operations = [
        migrations.RunPython(update_sector_vocabulary, re_update_sector_vocabulary),
    ]
