# Generated by Django 2.0.6 on 2018-09-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0011_aidtype_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidtype',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.Transaction'),
        ),
    ]
