# Generated by Django 2.0.13 on 2019-05-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0011_budgetnotprovided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetidentifier',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.BudgetIdentifierSector'),
        ),
    ]
