# Generated by Django 2.0.6 on 2019-02-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0011_update_sector_vocabulary'),
        ('iati_codelists', '0011_budgetnotprovided'),
    ]

    operations = [
    ]
