# Generated by Django 2.0.13 on 2019-05-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0012_budget_identifier_category_null_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidtype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.AidTypeCategory'),
        ),
    ]
