# Generated by Django 2.0.6 on 2018-09-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0013_auto_20180912_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidtype',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Transaction'),
        ),
    ]
