# Generated by Django 2.0.6 on 2018-09-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0014_auto_20180912_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidtype',
            name='transaction',
        ),
    ]
