# Generated by Django 2.0.13 on 2020-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_vocabulary', '0005_resultvocabulary'),
        ('iati_codelists', '0014_cashandvouchermodalities'),
    ]

    operations = [

        migrations.AlterField(
            model_name='aidtype',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='aidtype',
            unique_together={('code', 'vocabulary')},
        ),
    ]
