# Generated by Django 2.0.13 on 2020-03-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_vocabulary', '0005_resultvocabulary'),
        ('iati_codelists', '0015_auto_20200205_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('code', 'vocabulary')},
        ),
    ]
