# Generated by Django 2.0.13 on 2021-03-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0016_auto_20200310_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidtype',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
