# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationuser',
            name='iati_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
