# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationuser',
            name='organisation_admin_groups',
            field=models.ManyToManyField(blank=True, related_name='organisationuser_set', to='permissions.OrganisationAdminGroup', verbose_name=b'Organisation Admin Groups'),
        ),
        migrations.AddField(
            model_name='organisationuser',
            name='organisation_groups',
            field=models.ManyToManyField(blank=True, related_name='organisationuser_set', to='permissions.OrganisationGroup', verbose_name=b'Organisation Groups'),
        ),
    ]
