# Generated by Django 2.0.4 on 2018-04-30 14:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organisationadmingroup',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='organisationgroup',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='organisationuser',
            name='organisation_admin_groups',
            field=models.ManyToManyField(blank=True, related_name='organisationuser_set', to='permissions.OrganisationAdminGroup', verbose_name='Organisation Admin Groups'),
        ),
        migrations.AlterField(
            model_name='organisationuser',
            name='organisation_groups',
            field=models.ManyToManyField(blank=True, related_name='organisationuser_set', to='permissions.OrganisationGroup', verbose_name='Organisation Groups'),
        ),
    ]
