# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20161219_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisationuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
