# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20161031_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationadmingroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
