# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20170105_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationuser',
            name='iati_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
