# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_temp_turn_off_constraints'),
        ('iati_synchroniser', '0015_auto_20161025_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='OrganisationAdminGroup',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, db_constraint=True, to='iati_synchroniser.Publisher', unique=True)
        ),
        migrations.AlterField(
            model_name='OrganisationGroup',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, db_constraint=True, to='iati_synchroniser.Publisher', unique=True)
        )
    ]
