# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0002_auto_20170321_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='secondary_reporter',
            field=models.BooleanField(default=False),
        ),
    ]
