# Generated by Django 2.0.4 on 2018-04-30 14:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0004_activityparticipatingorganisation_org_activity_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysearch',
            name='text',
        ),
        migrations.AddField(
            model_name='activitysearch',
            name='search_vector_text',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='linked_data_uri',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activityparticipatingorganisation',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreportingorganisation',
            name='normalized_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='activitysearch',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitysearch',
            name='document_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitysearch',
            name='iati_identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activitysearch',
            name='participating_org',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitysearch',
            name='recipient_country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitysearch',
            name='recipient_region',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitysearch',
            name='reporting_org',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitysearch',
            name='sector',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitysearch',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crsaddloanterms',
            name='repayment_plan_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_hash',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='long_url',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='long_url_hash',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='point_srs_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='related_object_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='related object'),
        ),
        migrations.AlterField(
            model_name='otheridentifier',
            name='owner_ref',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='planneddisbursementprovider',
            name='normalized_ref',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='planneddisbursementprovider',
            name='primary_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='planneddisbursementprovider',
            name='provider_activity_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, null=True, verbose_name='provider-activity-id'),
        ),
        migrations.AlterField(
            model_name='planneddisbursementprovider',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='planneddisbursementreceiver',
            name='normalized_ref',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='planneddisbursementreceiver',
            name='primary_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='planneddisbursementreceiver',
            name='receiver_activity_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, null=True, verbose_name='receiver-activity-id'),
        ),
        migrations.AlterField(
            model_name='planneddisbursementreceiver',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='relatedactivity',
            name='ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resultindicatortitle',
            name='primary_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionprovider',
            name='normalized_ref',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='transactionprovider',
            name='primary_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='transactionprovider',
            name='provider_activity_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, null=True, verbose_name='provider-activity-id'),
        ),
        migrations.AlterField(
            model_name='transactionprovider',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='transactionreceiver',
            name='normalized_ref',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='transactionreceiver',
            name='primary_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='transactionreceiver',
            name='receiver_activity_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, null=True, verbose_name='receiver-activity-id'),
        ),
        migrations.AlterField(
            model_name='transactionreceiver',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddIndex(
            model_name='activitysearch',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_text'], name='iati_activi_search__168aa4_gin'),
        ),
    ]
