# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 11:29
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0004_activityparticipatingorganisation_org_activity_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysearch',
            name='search_vector_text',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='activitysearch',
            index=django.contrib.postgres.indexes.GinIndex(fields=[b'search_vector_text'], name='iati_activi_search__168aa4_gin'),
        ),
    ]
