# Generated by Django 2.0.6 on 2018-07-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0004_auto_20180430_1400'),
        ('iati', '0005_auto_20180430_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityparticipatingorganisation',
            name='crs_channel_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.CRSChannelCode'),
        ),
    ]
