# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0005_auto_20170831_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysearch',
            old_name='document_link_vector',
            new_name='document_link',
        ),
    ]
