# Generated by Django 2.0.6 on 2018-07-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_vocabulary', '0003_tagvocabulary'),
        ('iati', '0007_activitytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytag',
            name='code',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitytag',
            name='indicator_uri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='activitytag',
            name='vocabulary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iati_vocabulary.TagVocabulary'),
            preserve_default=False,
        ),
    ]
