# Generated by Django 2.0.6 on 2018-07-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0011_documentlink_result_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlink',
            name='result_indicator_baseline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_indicator_baselines', to='iati.ResultIndicator'),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='result_indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_indicators', to='iati.ResultIndicator'),
        ),
    ]
