# Generated by Django 2.0.6 on 2018-07-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0012_auto_20180720_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlink',
            name='period_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_targets', to='iati.ResultIndicator'),
        ),
    ]
