# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0012_auto_20151216_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityparticipatingorganisation',
            options={'verbose_name': 'Participating organisation', 'verbose_name_plural': 'Participating organisations'},
        ),
        migrations.AlterModelOptions(
            name='activitypolicymarker',
            options={'verbose_name': 'Policy marker', 'verbose_name_plural': 'Policy markers'},
        ),
        migrations.AlterModelOptions(
            name='activityrecipientcountry',
            options={'verbose_name': 'Recipient country', 'verbose_name_plural': 'Recipient countries'},
        ),
        migrations.AlterModelOptions(
            name='activityrecipientregion',
            options={'verbose_name': 'Recipient region', 'verbose_name_plural': 'Recipient regions'},
        ),
        migrations.AlterModelOptions(
            name='activityreportingorganisation',
            options={'verbose_name': 'Reporting organisation', 'verbose_name_plural': 'Reporting organisations'},
        ),
        migrations.AlterModelOptions(
            name='activitysector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_region_vocabulary',
        ),
        migrations.AlterField(
            model_name='activitydate',
            name='iso_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activityparticipatingorganisation',
            name='normalized_ref',
            field=models.CharField(db_index=True, default=None, max_length=120, null=True),
        ),
    ]
