# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0013_auto_20151223_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipatingorganisation',
            name='normalized_ref',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id_code',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='point_srs_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionprovider',
            name='ref',
            field=models.CharField(blank=True, default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='transactionreceiver',
            name='ref',
            field=models.CharField(blank=True, default=b'', max_length=250),
        ),
    ]
