# Generated by Django 2.0.6 on 2018-07-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0013_documentlink_period_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlink',
            name='period_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_actuals', to='iati.ResultIndicator'),
        ),
    ]
