# Generated by Django 2.0.6 on 2018-07-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_vocabulary', '0005_resultvocabulary'),
        ('iati', '0014_documentlink_period_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('vocabulary_uri', models.URLField(blank=True, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.Result')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_vocabulary.ResultVocabulary')),
            ],
        ),
    ]
