# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 13:01
from __future__ import unicode_literals

from django import db
from django.db import migrations, models
import django.db.models.deletion
import iati.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0013_auto_20151223_1622'),
    ]

    def create_search_indexes(apps, schema_editor):
        def create_search_index(column_name):
            schema_editor.execute("CREATE INDEX {table_name}_{column_name}_simple_tsv ON {table_name} USING gin({column_name});".format(table_name='iati_activitysearch', column_name=column_name))

        for column in ['title', 'description', 'reporting_org', 'recipient_country', 'recipient_region',
                'sector', 'document_link', 'participating_org']:
            create_search_index(column)

    def drop_search_indexes(apps, schema_editor):
        def drop_search_index(column_name):
            schema_editor.execute("DROP INDEX {table_name}_{column_name}_simple_tsv ;".format(table_name='iati_activitysearch'))

        for column in ['title', 'description', 'reporting_org', 'recipient_country', 'recipient_region',
                'sector', 'document_link', 'participating_org']:
            drop_search_index(column)

    operations = [
        migrations.CreateModel(
            name='ActivitySearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', iati.fields.TSVectorField()),
                ('title', iati.fields.TSVectorField()),
                ('description', iati.fields.TSVectorField()),
                ('reporting_org', iati.fields.TSVectorField()),
                ('recipient_country', iati.fields.TSVectorField()),
                ('recipient_region', iati.fields.TSVectorField()),
                ('sector', iati.fields.TSVectorField()),
                ('document_link', iati.fields.TSVectorField()),
                ('participating_org', iati.fields.TSVectorField()),
                ('last_reindexed', models.DateTimeField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iati.Activity')),
            ],
        ),
        migrations.RunPython(create_search_indexes, drop_search_indexes),
        migrations.AlterField(
            model_name='activityparticipatingorganisation',
            name='normalized_ref',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id_code',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='point_srs_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionprovider',
            name='ref',
            field=models.CharField(blank=True, default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='transactionreceiver',
            name='ref',
            field=models.CharField(blank=True, default=b'', max_length=250),
        ),
    ]
