# Generated by Django 2.0.6 on 2018-07-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0015_resultreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultindicator',
            name='aggregation_status',
            field=models.BooleanField(default=False),
        ),
    ]
