# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0016_auto_20160120_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentlinkcategory',
            options={'verbose_name_plural': 'Document link categories'},
        ),
        migrations.AlterField(
            model_name='activityparticipatingorganisation',
            name='primary_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resultindicatorperiod',
            name='actual',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='resultindicatorperiod',
            name='target',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.Region'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.TransactionType'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value_date',
            field=models.DateField(),
        ),
    ]
