# Generated by Django 2.0.6 on 2018-07-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0017_location_result_indicator_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlink',
            name='period_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_actual_document_links', to='iati.ResultIndicator'),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='period_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_target_document_links', to='iati.ResultIndicator'),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='result_indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_indicator_document_links', to='iati.ResultIndicator'),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='result_indicator_baseline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseline_document_links', to='iati.ResultIndicator'),
        ),
    ]
