# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0017_auto_20160121_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypolicymarker',
            name='significance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.PolicySignificance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activityreportingorganisation',
            name='normalized_ref',
            field=models.CharField(blank=True, db_index=True, default=b'', max_length=120),
        ),
        migrations.AlterField(
            model_name='relatedactivity',
            name='ref',
            field=models.CharField(blank=True, db_index=True, default=b'', max_length=200),
        ),
    ]
