# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0017_auto_20160121_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='hierarchy',
            field=models.SmallIntegerField(choices=[(1, 'Parent'), (2, 'Child')], db_index=True, default=1),
        ),
    ]
