# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0018_auto_20160204_1305'),
        ('iati', '0018_auto_20160202_1118'),
    ]

    operations = [
    ]
