# Generated by Django 2.0.6 on 2018-07-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0018_auto_20180726_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultIndicatorBaselineDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('result_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicator')),
            ],
        ),
    ]
