# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 15:20
from __future__ import unicode_literals

from django.db import migrations
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0019_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysearch',
            name='iati_identifier',
            field=djorm_pgfulltext.fields.VectorField(),
        ),
    ]
