# Generated by Django 2.0.6 on 2018-08-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0016_resultindicator_aggregation_status'),
        ('iati', '0019_resultindicatorbaselinedimension'),
    ]

    operations = [
    ]
