# Generated by Django 2.0.6 on 2018-08-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0020_resultindicatorperiodtarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultindicatorperiod',
            name='target',
        ),
    ]
