# Generated by Django 2.0.6 on 2018-08-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0021_remove_resultindicatorperiod_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultindicatorperiod',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicatorPeriodTarget'),
        ),
    ]
