# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0021_auto_20160217_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='xml_source_ref',
            field=models.CharField(db_index=True, default=b'', max_length=200),
        ),
    ]
