# Generated by Django 2.0.6 on 2018-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0022_resultindicatorperiod_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultindicatorperiodtarget',
            name='value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
