# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0022_auto_20160226_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
