# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0022_auto_20160226_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionprovider',
            name='provider_activity_ref',
            field=models.CharField(blank=True, db_index=True, default=b'', max_length=200, null=True, verbose_name=b'provider-activity-id'),
        ),
        migrations.AlterField(
            model_name='transactionreceiver',
            name='receiver_activity_ref',
            field=models.CharField(blank=True, db_index=True, default=b'', max_length=200, null=True, verbose_name=b'receiver-activity-id'),
        ),
    ]
