# Generated by Django 2.0.6 on 2018-08-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0023_auto_20180830_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultindicatorperiod',
            name='target',
        ),
        migrations.AddField(
            model_name='resultindicatorperiodtarget',
            name='result_indicator_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='iati.ResultIndicatorPeriod'),
        ),
    ]
