# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0023_transaction_xdr_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='planneddisbursement',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transactionrecipientcountry',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactionrecipientcountry',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transactionrecipientregion',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactionrecipientregion',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transactionsector',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='transactionsector',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
