# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 17:14
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0024_activitysearch_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='planneddisbursement',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='transactionrecipientcountry',
            name='reported_on_transaction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transactionrecipientcountry',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transactionrecipientregion',
            name='reported_on_transaction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transactionrecipientregion',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transactionsector',
            name='reported_on_transaction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transactionsector',
            name='xdr_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
