# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0024_auto_20160321_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecipientcountry',
            name='reported_on_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionrecipientregion',
            name='reported_on_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionsector',
            name='reported_on_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
