# Generated by Django 2.0.6 on 2018-08-30 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0024_auto_20180830_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultindicatorperiodtargetcomment',
            name='result_indicator_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicatorPeriod'),
        ),
    ]
