# Generated by Django 2.0.6 on 2018-08-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0025_auto_20180830_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultindicatorperiodtargetcomment',
            name='result_indicator_period',
        ),
        migrations.AddField(
            model_name='resultindicatorperiodtargetcomment',
            name='result_indicator_period_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicatorPeriodTarget'),
        ),
    ]
