# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0025_auto_20160406_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecipientcountry',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionrecipientregion',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionsector',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionrecipientregion',
            name='vocabulary',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_vocabulary.RegionVocabulary'),
        ),
        migrations.AlterField(
            model_name='transactionsector',
            name='vocabulary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_vocabulary.SectorVocabulary'),
        ),
    ]
