# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0025_auto_20160405_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecipientcountry',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='transactionrecipientregion',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='transactionsector',
            name='percentage',
        ),
    ]
