# Generated by Django 2.0.6 on 2018-08-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0026_auto_20180830_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultindicatorperiodtargetcomment',
            name='result_indicator_period_target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicatorPeriodTarget'),
            preserve_default=False,
        ),
    ]
