# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0026_convert_xdr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsector',
            name='vocabulary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_vocabulary.SectorVocabulary'),
        ),
    ]
