# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0027_convert_xdr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_country',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_region',
        ),
    ]
