# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:17
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0029_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='cad_value',
            field=models.DecimalField(decimal_places=7, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='eur_value',
            field=models.DecimalField(decimal_places=7, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='gbp_value',
            field=models.DecimalField(decimal_places=7, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='jpy_value',
            field=models.DecimalField(decimal_places=7, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='usd_value',
            field=models.DecimalField(decimal_places=7, default=Decimal('0'), max_digits=20),
        ),
    ]
