# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0030_auto_20160419_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='default_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='hierarchy',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Parent'), (2, 'Child')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='last_updated_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityreportingorganisation',
            name='organisation',
            field=models.ForeignKey(default='gb-1', on_delete=django.db.models.deletion.CASCADE, to='iati_organisation.Organisation'),
            preserve_default=False,
        ),
    ]
