# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0031_auto_20160421_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreportingorganisation',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iati_organisation.Organisation'),
        ),
    ]
