# Generated by Django 2.0.6 on 2018-08-31 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0032_resultindicatorperiodtargetdimension_result_indicator_period_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultindicatorperiodtargetdimension',
            name='result_indicator_period_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicatorPeriodTarget'),
        ),
    ]
