# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0033_auto_20160517_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(db_index=True),
        ),
    ]
