# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0034_auto_20160524_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultindicatortitle',
            name='primary_name',
            field=models.CharField(blank=True, db_index=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='resultindicatorperiod',
            name='actual',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resultindicatorperiod',
            name='target',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
