# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0038_vocabulary_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlink',
            name='iso_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
