# Generated by Django 2.0.6 on 2018-09-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0040_auto_20180906_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLinkDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iati.DocumentLink')),
            ],
        ),
    ]
