# Generated by Django 2.0.6 on 2018-09-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0010_aidtype_vocabulary'),
        ('iati', '0041_documentlinkdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.AidType')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.Transaction')),
            ],
        ),
    ]
