# Generated by Django 2.0.6 on 2018-09-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0041_documentlinkdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='aid_type',
        ),
    ]
