# Generated by Django 2.0.6 on 2018-09-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0042_transactionaidtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='aid_type',
        ),
    ]
