# Generated by Django 2.0.6 on 2018-09-13 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0015_remove_aidtype_transaction'),
        ('iati_vocabulary', '0005_resultvocabulary'),
        ('iati', '0042_remove_transaction_aid_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.AidType')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAidTypeVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_type_vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_vocabulary.AidTypeVocabulary')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.Transaction')),
            ],
        ),
    ]
