# Generated by Django 2.0.6 on 2018-09-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0010_aidtype_vocabulary'),
        ('iati', '0043_remove_transaction_aid_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDefaultAidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='default_aid_type',
        ),
        migrations.AddField(
            model_name='activitydefaultaidtype',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_aid_types', to='iati.Activity'),
        ),
        migrations.AddField(
            model_name='activitydefaultaidtype',
            name='aid_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.AidType'),
        ),
    ]
