# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0043_auto_20160606_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipatingorganisation',
            name='org_activity_id',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
