# Generated by Django 2.0.6 on 2018-09-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0010_aidtype_vocabulary'),
        ('iati', '0044_auto_20180917_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='default_aid_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.AidType'),
        ),
    ]
