# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0044_auto_20160607_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfotelephone',
            name='contact_info',
        ),
        migrations.AlterField(
            model_name='contactinfodepartment',
            name='contact_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='iati.ContactInfo'),
        ),
        migrations.AlterField(
            model_name='contactinfojobtitle',
            name='contact_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_title', to='iati.ContactInfo'),
        ),
        migrations.AlterField(
            model_name='contactinfomailingaddress',
            name='contact_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_address', to='iati.ContactInfo'),
        ),
        migrations.AlterField(
            model_name='contactinfoorganisation',
            name='contact_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='iati.ContactInfo'),
        ),
        migrations.AlterField(
            model_name='contactinfopersonname',
            name='contact_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='person_name', to='iati.ContactInfo'),
        ),
        migrations.DeleteModel(
            name='ContactInfoTelephone',
        ),
    ]
