# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0045_auto_20160613_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipatingorganisation',
            name='organisation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iati_organisation.Organisation'),
        ),
    ]
