# Generated by Django 2.0.6 on 2018-10-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0046_transaction_aid_type'),
        ('iati', '0020_merge_20180820_1534'),
    ]

    operations = [
    ]
