# Generated by Django 2.0.6 on 2018-10-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0046_transaction_aid_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultIndicatorBaseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('iso_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resultindicator',
            name='baseline_value',
        ),
        migrations.RemoveField(
            model_name='resultindicator',
            name='baseline_year',
        ),
        migrations.AddField(
            model_name='resultindicatorbaseline',
            name='result_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicator'),
        ),
    ]
