# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0048_add_budget_sector_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planneddisbursement',
            name='period_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
