# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 17:14
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.management import update_contenttypes


def clean_default_lang(apps, schema_editor):
    """
    convert all transaction's xdr values
    takes ~20 mins
    """
    update_contenttypes(apps.get_app_config('iati'), interactive=False) # make sure all content types exist

    try: # don't run on first migration
        Activity = apps.get_model('iati', 'Activity')
        Language = apps.get_model('iati_codelists', 'Language')
        languages = Language.objects.all().values('code')
        Activity.objects.exclude(default_lang__in=languages).exclude(default_lang=None).update(default_lang=None)
    except:
        return



class Migration(migrations.Migration):
    dependencies = [
        ('iati', '0050_auto_20160622_1650'),
    ]

    operations = [
        migrations.RunPython(clean_default_lang),
    ]
