# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-10 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0050_auto_20160622_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='default_lang',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.Language'),
        ),
    ]
