# Generated by Django 2.0.6 on 2018-11-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0051_resultindicatorbaselinedimension_result_indicator_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultindicatorbaselinedimension',
            name='result_indicator_baseline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicatorBaseline'),
        ),
    ]
