# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-18 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0052_default_lang_and_published_bool'),
        ('iati', '0051_default_lang_fk_clean'),
    ]

    operations = [
    ]
