# Generated by Django 2.0.6 on 2018-11-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0052_auto_20181108_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultindicatorbaselinecomment',
            name='result_indicator',
        ),
        migrations.AddField(
            model_name='resultindicatorbaselinecomment',
            name='result_indicator_baseline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicatorBaseline'),
        ),
    ]
