# Generated by Django 2.0.6 on 2018-11-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0053_auto_20181108_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultindicatorbaselinecomment',
            name='result_indicator_baseline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iati.ResultIndicatorBaseline'),
        ),
    ]
