# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0055_auto_20161024_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationadmingroup',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='organisationadmingroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='organisationadmingroup',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='organisationgroup',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='organisationgroup',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='OrganisationAdminGroup',
        ),
        migrations.DeleteModel(
            name='OrganisationGroup',
        ),
    ]
