# Generated by Django 2.0.6 on 2018-11-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0055_auto_20181108_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlink',
            name='period_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_target_document_links', to='iati.ResultIndicatorPeriodTarget'),
        ),
    ]
