
# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_synchroniser', '0020_auto_20161027_0115'),
        ('iati', '0056_auto_20161025_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='dataset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_synchroniser.Dataset'),
        ),
    ]
