# Generated by Django 2.0.6 on 2018-11-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0056_auto_20181109_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentlink',
            old_name='period_target',
            new_name='result_indicator_period_target',
        ),
    ]
