# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-08 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0057_auto_20161027_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationactivitydescription',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_description', to='iati.Location'),
        ),
        migrations.AlterField(
            model_name='locationdescription',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='iati.Location'),
        ),
        migrations.AlterField(
            model_name='locationname',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='iati.Location'),
        ),
    ]
