# Generated by Django 2.0.6 on 2018-11-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0057_auto_20181109_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentlink',
            name='period_actual',
        ),
        migrations.AddField(
            model_name='documentlink',
            name='result_indicator_period_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_actual_document_links', to='iati.ResultIndicatorPeriodActual'),
        ),
    ]
