# Generated by Django 2.0.6 on 2018-12-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0048_manual_location_result_indicator_baseline'),
        ('iati', '0058_auto_20181109_1520'),
    ]

    operations = [
    ]
