# Generated by Django 2.0.6 on 2019-01-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0058_auto_20181109_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crsaddloanterms',
            name='repayment_plan_text',
        ),
    ]
