# Generated by Django 2.0.6 on 2019-01-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati_codelists', '0011_budgetnotprovided'),
        ('iati', '0059_remove_crsaddloanterms_repayment_plan_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='budget_not_provided',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.BudgetNotProvided'),
        ),
    ]
