# Generated by Django 2.0.6 on 2019-02-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0060_activity_budget_not_provided'),
        ('iati', '0059_merge_20181212_1649'),
    ]

    operations = [
    ]
