# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-12 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0060_auto_20161208_1538'),
    ]

    def remove_conditions(apps, schema_editor):
        try: # don't run on first migration
            Condition = apps.get_model('iati', 'Condition')
        except:
            return

        Condition.objects.all().delete()

    operations = [
        migrations.RunPython(remove_conditions),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached', models.BooleanField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.Activity')),
            ],
        ),
        migrations.RemoveField(
            model_name='condition',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='text',
        ),
        migrations.RemoveField(
            model_name='crsaddotherflags',
            name='other_flags_significance',
        ),
        migrations.AddField(
            model_name='crsadd',
            name='channel_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crsaddotherflags',
            name='significance',
            field=models.BooleanField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crsaddloanstatus',
            name='crs_add',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_status', to='iati.CrsAdd'),
        ),
        migrations.AlterField(
            model_name='crsaddloanterms',
            name='crs_add',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_terms', to='iati.CrsAdd'),
        ),
        migrations.AlterField(
            model_name='crsaddloanterms',
            name='rate_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='crsaddloanterms',
            name='rate_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='crsaddotherflags',
            name='crs_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_flags', to='iati.CrsAdd'),
        ),
        migrations.AlterField(
            model_name='fss',
            name='extraction_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fssforecast',
            name='value_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fssforecast',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='condition',
            name='conditions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iati.Conditions'),
            preserve_default=False,
        ),
    ]
