# Generated by Django 2.0.6 on 2019-03-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0061_udpated_activity_search_to_add_some_new_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysearch',
            name='tag',
        ),
    ]
