# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0062_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='modified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='ready_to_publish',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='publisher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_synchroniser.Publisher'),
        ),
    ]
