# Generated by Django 2.0.6 on 2019-03-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0062_remove_activitysearch_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysearch',
            old_name='condition',
            new_name='conditions',
        ),
    ]
