# Generated by Django 2.0.13 on 2019-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0063_renamed_condition_to_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_id_code',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='point_srs_name',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='ref',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
