# Generated by Django 2.0.13 on 2019-08-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0063_renamed_condition_to_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='default_aid_type',
        ),
    ]
