# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0064_added_manually'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField(default=b'', max_length=500)),
                ('url_is_valid', models.BooleanField(default=False)),
                ('document_name', models.CharField(default=b'', max_length=500)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('document_content', models.TextField(default=b'')),
                ('long_url_hash', models.CharField(default=b'', max_length=500)),
                ('file_hash', models.CharField(default=b'', max_length=500)),
                ('document_or_long_url_changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('document_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iati.DocumentLink')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djorm_pgfulltext.fields.VectorField()),
                ('text', djorm_pgfulltext.fields.VectorField()),
                ('last_reindexed', models.DateTimeField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iati.Document')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='document',
            index_together=set([('created_at', 'id')]),
        ),
    ]
