# Generated by Django 2.0.13 on 2021-01-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0005_auto_20181217_1712'),
        ('iati_vocabulary', '0005_resultvocabulary'),
        ('iati', '0063_renamed_condition_to_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRecipientCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.Budget')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.Country')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetRecipientRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary_uri', models.URLField(blank=True, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.Budget')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.Region')),
                ('vocabulary', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_vocabulary.RegionVocabulary')),
            ],
        ),
    ]
