# Generated by Django 2.0.13 on 2019-08-07 17:31

from django.db import migrations
from django.core import management


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0063_renamed_condition_to_conditions'),
    ]

    operations = [
        management.call_command(
            'migration_default_aid_type_to_default_aid_types',
            verbosity=0
        )
        ,
        migrations.RemoveField(
            model_name='activity',
            name='default_aid_type',
        ),
    ]
