
# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0063_auto_20170109_1357'),
    ]

    def banarieomeharie(apps, schema_editor):
        try: # don't run on first migration
            Dataset = apps.get_model('iati_synchroniser', 'Dataset')
        except:
            return

        Dataset.objects.all().update(added_manually=False)

    operations = [
        migrations.RunPython(banarieomeharie),
    ]
