# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0064_auto_20170111_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iati.Activity'),
        ),
    ]
