# Generated by Django 2.0.13 on 2019-08-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0064_remove_activity_default_aid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydefaultaidtype',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_aid_type', to='iati.Activity'),
        ),
    ]
