# Generated by Django 2.0.13 on 2019-09-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0065_auto_20190904_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crsadd',
            name='channel_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iati_codelists.CRSChannelCode'),
        ),
    ]
