# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0066_auto_20170127_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecipientcountry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_country', to='iati.Transaction'),
        ),
    ]
