# Generated by Django 2.0.13 on 2019-09-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0066_auto_20190916_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipatingorganisation',
            name='ref',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
