# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0067_transactionrecipientcountry_reported_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecipientregion',
            name='reported_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_recipient_region', to='iati.Transaction'),
        ),
        migrations.AddField(
            model_name='transactionsector',
            name='reported_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sector', to='iati.Transaction'),
        ),
    ]
