# Generated by Django 2.0.13 on 2019-10-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0067_auto_20190926_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='point_srs_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
