# Generated by Django 2.0.13 on 2020-02-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0068_point_srs_name_null_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultindicatorperiodactual',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resultindicatorperiodtarget',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
