# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0068_auto_20170206_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecipientcountry',
            name='reported_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_recipient_country', to='iati.Transaction'),
        ),
        migrations.AlterField(
            model_name='transactionrecipientcountry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.Transaction'),
        ),
    ]
