# Generated by Django 2.0.13 on 2019-11-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0069_namespaceelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespaceelement',
            name='sub_element',
            field=models.BooleanField(default=False),
        ),
    ]
