# Generated by Django 2.0.13 on 2019-11-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0070_namespaceelement_sub_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespaceelement',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iati.Activity'),
        ),
    ]
