# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0070_auto_20170207_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecipientcountry',
            name='reported_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_recipient_country', to='iati.Transaction'),
        ),
    ]
