# Generated by Django 2.0.13 on 2020-03-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0069_auto_20200225_1416'),
        ('iati', '0071_namespaceelement_activity'),
    ]

    operations = [
    ]
