# Generated by Django 2.0.13 on 2020-10-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0072_auto_20201020_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='imf_url',
            field=models.TextField(null=True),
        ),
    ]
