# Generated by Django 2.0.13 on 2020-11-06 13:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0075_auto_20201020_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='usd_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='planneddisbursement',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='planneddisbursement',
            name='usd_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usd_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
    ]
