# Generated by Django 2.0.13 on 2021-01-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0076_auto_20201106_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytag',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
