# Generated by Django 2.0.13 on 2021-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0077_auto_20210111_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sha1',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
