# Generated by Django 2.0.13 on 2021-09-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0079_auto_20210903_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityaggregation',
            name='budget_value_usd',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='activitypluschildaggregation',
            name='budget_value_usd',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='childaggregation',
            name='budget_value_usd',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
