# Generated by Django 4.1.6 on 2023-02-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='MonthlyAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('imf_url', models.URLField(max_length=2000, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=20, null=True)),
                ('currency', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='legacy_currency_convert.currency'
                )),
            ],
            options={
                'unique_together': {('currency', 'month', 'year')},
            },
        ),
    ]
