# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetIdentifierVocabulary',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='GeographicVocabulary',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default=b'')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HumanitarianScopeVocabulary',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorVocabulary',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default=b'')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyMarkerVocabulary',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='RegionVocabulary',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='SectorVocabulary',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default=b'')),
                ('url', models.URLField()),
            ],
        ),
    ]
