# Generated by Django 2.0.4 on 2018-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetidentifiervocabulary',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='geographicvocabulary',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='humanitarianscopevocabulary',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='indicatorvocabulary',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='policymarkervocabulary',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='regionvocabulary',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sectorvocabulary',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
