# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_vocabulary', '0002_auto_20160602_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionvocabulary',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
