# Generated by Django 2.0.6 on 2018-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_vocabulary', '0003_tagvocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidTypeVocabulary',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
