# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati_vocabulary', '0003_auto_20160602_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanitarianscopevocabulary',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
