# Generated by Django 2.0.4 on 2018-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainlinkrelation',
            name='from_node',
            field=models.CharField(choices=[('start_node', 'Start node'), ('end_node', 'End node')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chainlinkrelation',
            name='relation',
            field=models.CharField(choices=[('incoming_fund', 'Incoming Fund'), ('disbursement', 'Disbursement'), ('expenditure', 'Expenditure'), ('incoming_commitment', 'Incoming commitment'), ('outgoing_commitment', 'Outgoing commitment'), ('expenditure', 'Expenditure'), ('parent', 'Parent'), ('child', 'Child')], max_length=30),
        ),
        migrations.AlterField(
            model_name='chainnodeerror',
            name='error_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chainnodeerror',
            name='warning_level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=255),
        ),
    ]
