# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_auto_20170322_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainnode',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
