# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0003_auto_20170322_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainnode',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chainnode',
            name='level',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
