# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0004_auto_20170322_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chainnode',
            old_name='level',
            new_name='tier',
        ),
    ]
