# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0005_auto_20170323_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainlink',
            name='end_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_link', to='traceability.ChainNode'),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='start_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_link', to='traceability.ChainNode'),
        ),
    ]
