# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0006_auto_20170323_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainnode',
            name='treated_as_end_node',
            field=models.BooleanField(default=False),
        ),
    ]
